name: Generate RSS Feed

on:
  push:
    paths:
      - 'artikel-pr.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate RSS feed
        run: python generate_feed.py

      - name: Commit and push feed.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          git commit -m "Auto update feed.xml"
          git push
